import QtQuick

QtObject {
    // dst groups:
    //   "namerica"  - 2nd Sunday Mar → 1st Sunday Nov (+1h)
    //   "europe"    - Last Sunday Mar → Last Sunday Oct (+1h)
    //   "australia"  - 1st Sunday Oct → 1st Sunday Apr (+1h)
    //   "nz"        - Last Sunday Sep → 1st Sunday Apr (+1h)
    //   ""          - No DST

    property var timezones: [
        { id: "Pacific/Midway", city: "Midway", country: "US", offset: -11.0, dst: "" },
        { id: "Pacific/Honolulu", city: "Honolulu", country: "US", offset: -10.0, dst: "" },
        { id: "America/Anchorage", city: "Anchorage", country: "US", offset: -9.0, dst: "namerica" },
        { id: "America/Los_Angeles", city: "Los Angeles", country: "US", offset: -8.0, dst: "namerica" },
        { id: "America/Vancouver", city: "Vancouver", country: "CA", offset: -8.0, dst: "namerica" },
        { id: "America/Tijuana", city: "Tijuana", country: "MX", offset: -8.0, dst: "namerica" },
        { id: "America/Phoenix", city: "Phoenix", country: "US", offset: -7.0, dst: "" },
        { id: "America/Denver", city: "Denver", country: "US", offset: -7.0, dst: "namerica" },
        { id: "America/Edmonton", city: "Edmonton", country: "CA", offset: -7.0, dst: "namerica" },
        { id: "America/Chicago", city: "Chicago", country: "US", offset: -6.0, dst: "namerica" },
        { id: "America/Mexico_City", city: "Mexico City", country: "MX", offset: -6.0, dst: "" },
        { id: "America/Winnipeg", city: "Winnipeg", country: "CA", offset: -6.0, dst: "namerica" },
        { id: "America/Guatemala", city: "Guatemala City", country: "GT", offset: -6.0, dst: "" },
        { id: "America/New_York", city: "New York", country: "US", offset: -5.0, dst: "namerica" },
        { id: "America/Toronto", city: "Toronto", country: "CA", offset: -5.0, dst: "namerica" },
        { id: "America/Bogota", city: "Bogotá", country: "CO", offset: -5.0, dst: "" },
        { id: "America/Lima", city: "Lima", country: "PE", offset: -5.0, dst: "" },
        { id: "America/Indianapolis", city: "Indianapolis", country: "US", offset: -5.0, dst: "namerica" },
        { id: "America/Atlanta", city: "Atlanta", country: "US", offset: -5.0, dst: "namerica" },
        { id: "America/Detroit", city: "Detroit", country: "US", offset: -5.0, dst: "namerica" },
        { id: "America/Panama", city: "Panama City", country: "PA", offset: -5.0, dst: "" },
        { id: "America/Caracas", city: "Caracas", country: "VE", offset: -4.0, dst: "" },
        { id: "America/Halifax", city: "Halifax", country: "CA", offset: -4.0, dst: "namerica" },
        { id: "America/Santiago", city: "Santiago", country: "CL", offset: -4.0, dst: "" },
        { id: "America/La_Paz", city: "La Paz", country: "BO", offset: -4.0, dst: "" },
        { id: "Atlantic/Bermuda", city: "Hamilton", country: "BM", offset: -4.0, dst: "namerica" },
        { id: "America/St_Johns", city: "St. John's", country: "CA", offset: -3.5, dst: "namerica" },
        { id: "America/Sao_Paulo", city: "São Paulo", country: "BR", offset: -3.0, dst: "" },
        { id: "America/Buenos_Aires", city: "Buenos Aires", country: "AR", offset: -3.0, dst: "" },
        { id: "America/Montevideo", city: "Montevideo", country: "UY", offset: -3.0, dst: "" },
        { id: "Atlantic/South_Georgia", city: "South Georgia", country: "GS", offset: -2.0, dst: "" },
        { id: "Atlantic/Azores", city: "Azores", country: "PT", offset: -1.0, dst: "europe" },
        { id: "Atlantic/Cape_Verde", city: "Cape Verde", country: "CV", offset: -1.0, dst: "" },
        { id: "Europe/London", city: "London", country: "GB", offset: 0.0, dst: "europe" },
        { id: "Europe/Dublin", city: "Dublin", country: "IE", offset: 0.0, dst: "europe" },
        { id: "Europe/Lisbon", city: "Lisbon", country: "PT", offset: 0.0, dst: "europe" },
        { id: "Africa/Casablanca", city: "Casablanca", country: "MA", offset: 0.0, dst: "" },
        { id: "Africa/Accra", city: "Accra", country: "GH", offset: 0.0, dst: "" },
        { id: "Atlantic/Reykjavik", city: "Reykjavik", country: "IS", offset: 0.0, dst: "" },
        { id: "Europe/Paris", city: "Paris", country: "FR", offset: 1.0, dst: "europe" },
        { id: "Europe/Berlin", city: "Berlin", country: "DE", offset: 1.0, dst: "europe" },
        { id: "Europe/Rome", city: "Rome", country: "IT", offset: 1.0, dst: "europe" },
        { id: "Europe/Madrid", city: "Madrid", country: "ES", offset: 1.0, dst: "europe" },
        { id: "Europe/Amsterdam", city: "Amsterdam", country: "NL", offset: 1.0, dst: "europe" },
        { id: "Europe/Brussels", city: "Brussels", country: "BE", offset: 1.0, dst: "europe" },
        { id: "Europe/Vienna", city: "Vienna", country: "AT", offset: 1.0, dst: "europe" },
        { id: "Europe/Zurich", city: "Zurich", country: "CH", offset: 1.0, dst: "europe" },
        { id: "Europe/Stockholm", city: "Stockholm", country: "SE", offset: 1.0, dst: "europe" },
        { id: "Europe/Oslo", city: "Oslo", country: "NO", offset: 1.0, dst: "europe" },
        { id: "Europe/Copenhagen", city: "Copenhagen", country: "DK", offset: 1.0, dst: "europe" },
        { id: "Europe/Warsaw", city: "Warsaw", country: "PL", offset: 1.0, dst: "europe" },
        { id: "Europe/Prague", city: "Prague", country: "CZ", offset: 1.0, dst: "europe" },
        { id: "Europe/Budapest", city: "Budapest", country: "HU", offset: 1.0, dst: "europe" },
        { id: "Africa/Lagos", city: "Lagos", country: "NG", offset: 1.0, dst: "" },
        { id: "Europe/Athens", city: "Athens", country: "GR", offset: 2.0, dst: "europe" },
        { id: "Europe/Bucharest", city: "Bucharest", country: "RO", offset: 2.0, dst: "europe" },
        { id: "Europe/Helsinki", city: "Helsinki", country: "FI", offset: 2.0, dst: "europe" },
        { id: "Europe/Kyiv", city: "Kyiv", country: "UA", offset: 2.0, dst: "europe" },
        { id: "Africa/Cairo", city: "Cairo", country: "EG", offset: 2.0, dst: "" },
        { id: "Africa/Johannesburg", city: "Johannesburg", country: "ZA", offset: 2.0, dst: "" },
        { id: "Asia/Jerusalem", city: "Jerusalem", country: "IL", offset: 2.0, dst: "" },
        { id: "Asia/Beirut", city: "Beirut", country: "LB", offset: 2.0, dst: "europe" },
        { id: "Europe/Istanbul", city: "Istanbul", country: "TR", offset: 3.0, dst: "" },
        { id: "Europe/Moscow", city: "Moscow", country: "RU", offset: 3.0, dst: "" },
        { id: "Asia/Baghdad", city: "Baghdad", country: "IQ", offset: 3.0, dst: "" },
        { id: "Asia/Kuwait", city: "Kuwait City", country: "KW", offset: 3.0, dst: "" },
        { id: "Asia/Riyadh", city: "Riyadh", country: "SA", offset: 3.0, dst: "" },
        { id: "Asia/Doha", city: "Doha", country: "QA", offset: 3.0, dst: "" },
        { id: "Africa/Nairobi", city: "Nairobi", country: "KE", offset: 3.0, dst: "" },
        { id: "Asia/Tehran", city: "Tehran", country: "IR", offset: 3.5, dst: "" },
        { id: "Asia/Dubai", city: "Dubai", country: "AE", offset: 4.0, dst: "" },
        { id: "Asia/Muscat", city: "Muscat", country: "OM", offset: 4.0, dst: "" },
        { id: "Asia/Baku", city: "Baku", country: "AZ", offset: 4.0, dst: "" },
        { id: "Asia/Kabul", city: "Kabul", country: "AF", offset: 4.5, dst: "" },
        { id: "Asia/Karachi", city: "Karachi", country: "PK", offset: 5.0, dst: "" },
        { id: "Asia/Tashkent", city: "Tashkent", country: "UZ", offset: 5.0, dst: "" },
        { id: "Asia/Kolkata", city: "Kolkata", country: "IN", offset: 5.5, dst: "" },
        { id: "Asia/Mumbai", city: "Mumbai", country: "IN", offset: 5.5, dst: "" },
        { id: "Asia/Delhi", city: "Delhi", country: "IN", offset: 5.5, dst: "" },
        { id: "Asia/Colombo", city: "Colombo", country: "LK", offset: 5.5, dst: "" },
        { id: "Asia/Kathmandu", city: "Kathmandu", country: "NP", offset: 5.75, dst: "" },
        { id: "Asia/Dhaka", city: "Dhaka", country: "BD", offset: 6.0, dst: "" },
        { id: "Asia/Almaty", city: "Almaty", country: "KZ", offset: 6.0, dst: "" },
        { id: "Asia/Yangon", city: "Yangon", country: "MM", offset: 6.5, dst: "" },
        { id: "Asia/Bangkok", city: "Bangkok", country: "TH", offset: 7.0, dst: "" },
        { id: "Asia/Jakarta", city: "Jakarta", country: "ID", offset: 7.0, dst: "" },
        { id: "Asia/Ho_Chi_Minh", city: "Ho Chi Minh City", country: "VN", offset: 7.0, dst: "" },
        { id: "Asia/Shanghai", city: "Shanghai", country: "CN", offset: 8.0, dst: "" },
        { id: "Asia/Beijing", city: "Beijing", country: "CN", offset: 8.0, dst: "" },
        { id: "Asia/Hong_Kong", city: "Hong Kong", country: "HK", offset: 8.0, dst: "" },
        { id: "Asia/Singapore", city: "Singapore", country: "SG", offset: 8.0, dst: "" },
        { id: "Asia/Taipei", city: "Taipei", country: "TW", offset: 8.0, dst: "" },
        { id: "Asia/Manila", city: "Manila", country: "PH", offset: 8.0, dst: "" },
        { id: "Asia/Kuala_Lumpur", city: "Kuala Lumpur", country: "MY", offset: 8.0, dst: "" },
        { id: "Australia/Perth", city: "Perth", country: "AU", offset: 8.0, dst: "" },
        { id: "Asia/Tokyo", city: "Tokyo", country: "JP", offset: 9.0, dst: "" },
        { id: "Asia/Seoul", city: "Seoul", country: "KR", offset: 9.0, dst: "" },
        { id: "Australia/Adelaide", city: "Adelaide", country: "AU", offset: 9.5, dst: "australia" },
        { id: "Australia/Darwin", city: "Darwin", country: "AU", offset: 9.5, dst: "" },
        { id: "Australia/Sydney", city: "Sydney", country: "AU", offset: 10.0, dst: "australia" },
        { id: "Australia/Melbourne", city: "Melbourne", country: "AU", offset: 10.0, dst: "australia" },
        { id: "Australia/Brisbane", city: "Brisbane", country: "AU", offset: 10.0, dst: "" },
        { id: "Pacific/Guam", city: "Guam", country: "GU", offset: 10.0, dst: "" },
        { id: "Pacific/Noumea", city: "Nouméa", country: "NC", offset: 11.0, dst: "" },
        { id: "Pacific/Auckland", city: "Auckland", country: "NZ", offset: 12.0, dst: "nz" },
        { id: "Pacific/Fiji", city: "Suva", country: "FJ", offset: 12.0, dst: "" },
        { id: "Pacific/Tongatapu", city: "Nuku'alofa", country: "TO", offset: 13.0, dst: "" },
        { id: "Pacific/Apia", city: "Apia", country: "WS", offset: 13.0, dst: "" },
        { id: "Pacific/Kiritimati", city: "Kiritimati", country: "KI", offset: 14.0, dst: "" }
    ]
}
